[package]
name = "par_io"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
print_ptr = [] # print buffer memory address to verify that no new allocation happens
